apiVersion: v1
kind: Service
metadata:
  name: almond-backend
  labels:
    app: almond-backend
spec:
  ports:
  - port: 8100
    protocol: TCP
  clusterIP: None
  selector:
    app: almond-backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "almond-backend"
spec:
  selector:
    matchLabels:
      app: "almond-backend"
  replicas: 2
  serviceName: almond-backend
  template:
    metadata:
      labels:
        app: "almond-backend"
    spec:
      containers:
      - name: "main"
        image: stanfordoval/almond-cloud:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: THINGENGINE_DISABLE_SANDBOX
          value: "1"
        args: ["run-almond", "--k8s"]
        workingDir: /srv/thingengine
        volumeMounts:
        - name: almond-user-data
          mountPath: "/srv/thingengine"
          readOnly: false
        - name: config
          mountPath: "/etc/almond-cloud"
          readOnly: true
        resources:
          requests:
            memory: 200M
        ports:
          - containerPort: 8100
            name: almond
        readinessProbe:
          tcpSocket:
            port: 8100
          periodSeconds: 20
      volumes:
      - name: config
        configMap:
          name: almond-config
  volumeClaimTemplates:
  - metadata:
      name: almond-user-data
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 2G
