apiVersion: apps/v1
kind: Deployment
metadata:
  name: "training"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "training"
  template:
    metadata:
      labels:
        app: "training"
    spec:
      containers:
      - name: "training"
        image: stanfordoval/almond-cloud:latest-decanlp
        imagePullPolicy: Always
        args: ["run-training"]
        volumeMounts:
        - name: config
          mountPath: "/etc/almond-cloud"
          readOnly: true
        - name: aws
          mountPath: "/home/almond-cloud/.aws"
          readOnly: true
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
              - NET_ADMIN
        resources:
          requests:
            memory: 32G
            ephemeral-storage: 40G
        readinessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: config
        secret:
          secretName: almond-config
      - name: aws
        secret:
          secretName: aws-config
---
apiVersion: v1
kind: Service
metadata:
  name: "training"
spec:
  ports:
  - port: 8090
    protocol: TCP
  selector:
    app: "training"
